# Generated by Django 4.1 on 2022-12-22 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='date_added',
            field=models.DateField(auto_now_add=True, null=True),
        ),
    ]
