# Generated by Django 4.1 on 2022-12-22 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_texts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='about_text',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='texts',
            name='intro_text',
            field=models.TextField(),
        ),
    ]
