# Generated by Django 4.1 on 2022-12-22 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_texts_about_text_alter_texts_intro_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
