# Generated by Django 4.1 on 2023-02-21 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0007_alter_resume_resume_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='texts',
            name='greetings_text',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
