# Generated by Django 4.1 on 2022-09-22 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(default=1, upload_to='images/project_thumbnails'),
            preserve_default=False,
        ),
    ]
