# Generated by Django 4.1 on 2022-12-22 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0002_project_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='date_added',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
