# Generated by Django 4.1 on 2022-09-22 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_project_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='thumbnail',
            field=models.ImageField(upload_to='./main_app/static/images/project'),
        ),
    ]
