# Generated by Django 4.1 on 2023-01-19 06:03

from django.db import migrations
import django_quill.fields


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0003_alter_project_date_added'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='description',
            field=django_quill.fields.QuillField(),
        ),
    ]
