# Generated by Django 4.1 on 2023-02-20 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0005_alter_project_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
