# Generated by Django 4.2.2 on 2023-06-27 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects_app', '0007_projecttag_project_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='demoPassword',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='demoUsername',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
