# Generated by Django 4.1 on 2022-12-22 18:24

from django.db import migrations, models
import django_quill.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=80)),
                ('subtitle', models.CharField(max_length=500)),
                ('thumbnail', models.ImageField(upload_to='blog')),
                ('body', django_quill.fields.QuillField()),
                ('date_posted', models.DateTimeField(auto_now_add=True)),
                ('featured_article', models.BooleanField(default=False)),
                ('slug', models.SlugField(null=True)),
                ('tags', models.ManyToManyField(blank=True, null=True, to='blog_app.tag')),
            ],
        ),
    ]
