# Generated by Django 4.1 on 2023-02-20 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog_app', '0003_alter_article_date_added'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='ordering',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
